In [38]:
import urllib
url="https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
filename="input.txt"
urllib.request.urlretrieve(url,filename)

('input.txt', <http.client.HTTPMessage at 0x21a0d24c910>)

In [39]:
with open("input.txt",'r',encoding="utf-8") as f: #utf-8 encoding takes 1-4 bytes per character(variable) unlike ASCII that takes 8 bits per character
  text=f.read()                                   #highly relevant for tokenizers

In [40]:
print("The length of the dataset is:", len(text))

The length of the dataset is: 1115394


In [41]:
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [42]:
chars=sorted(set(text))
seen_string="".join(chars)
print(seen_string)
vocab_size=len(chars)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


In [43]:
stoi={ch:i for i,ch in enumerate(chars)}
print(stoi)#string to integer
itos={i:ch for i,ch in enumerate(chars)}
print(itos)#integer to string

def encode(s): #Any string can be converted into a list of numbers(based on stoi dict)
  string_val=[]
  for i in s:
    string_val.append(stoi[i])
  return string_val

def decode(i): #Any set of numbers can be converted into a string(based on itos dict)
  string_val=""
  for k in i:
    string_val+=(itos[k])
  return string_val


print(encode("hi there"))
print(decode(encode("hi there")))

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}
{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i',

In [44]:
import torch
data=torch.tensor(encode(text),dtype=torch.long)
print(data.shape,data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [45]:
n=int(0.9*len(data))
train_data=data[:n]
val_data=data[n:]

In [46]:
block_size=8

In [47]:
x=train_data[:block_size]#sliding window 0-7
y=train_data[1:block_size+1]# sliding window 1-8
print(x)
print(y)

tensor([18, 47, 56, 57, 58,  1, 15, 47])
tensor([47, 56, 57, 58,  1, 15, 47, 58])


In [48]:
for t in range(block_size):
  context=x[:t+1]
  target=y[t]
  print(f"when input is {context}, output is {target}")

when input is tensor([18]), output is 47
when input is tensor([18, 47]), output is 56
when input is tensor([18, 47, 56]), output is 57
when input is tensor([18, 47, 56, 57]), output is 58
when input is tensor([18, 47, 56, 57, 58]), output is 1
when input is tensor([18, 47, 56, 57, 58,  1]), output is 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]), output is 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), output is 58


In [49]:
torch.manual_seed(1337)
batch_size=4 #How many independent sequences will we process in parallel?
block_size=8
def get_batch(split):
  #generate a small batch of data of inputs x and targets y
  new_data=train_data if split=='train' else val_data
  ix=torch.randint(len(new_data)-block_size,(batch_size,))#Taking 4 random numbers
  x=torch.stack([new_data[i:i+block_size] for i in ix]) #  Randomly taking continuous block_size length chunk form the data(batch size(4) of them and stacking)
  y=torch.stack([new_data[i+1:i+block_size+1] for i in ix] )
  return x,y

In [50]:
xb,yb=get_batch('train')
print("inputs:")
print(xb.shape)
print(xb)
print("outputs:")
print(yb.shape)
print(yb)

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
outputs:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


In [57]:
# BIGRAM EMBEDDING TABLE (vocab_size × vocab_size)
# How the Lookup Happens
# Now, let's say the network is processing the letter "H" (Integer ID: 34).
# PyTorch takes the number 34.
# It walks up to that giant 65 x 32 spreadsheet.
# It goes directly to Row 34.
# It completely ignores all other rows. It scoops up the 32 decimal numbers sitting in Row 34.
# It hands that list of 32 numbers to the rest of the Transformer.
#This is the embedding layer

#NOW ITS JUST CHANNELS AND NOT ALL VOCAB SIZE
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)
n_embd=32

#Each token has its position embedding and token embedding(feature vector). Both are added together to get the final embedding for that token.
# 1. The Starting Grid (idx)
# You pass in the text. Let's say the tokens are the integers [2, 5, 8].

# The Grid: A single flat row of 3 numbers.

# Shape: (1, 3) — [Batch=1, Time=3]

# 2. The Token Stretch (tok_emb)
# Code: tok_emb = self.token_embedding_table(idx)
# The model cannot do math on a flat row of integers. It stretches each integer downward into a column of 4 decimals.

# The integer 2 turns into [0.1, -0.2, 0.5, 0.0].

# The integer 5 turns into [0.9, 0.1, -0.4, 0.3].

# The integer 8 turns into [-0.1, 0.8, 0.2, 0.1].

# The Grid: You now have a rectangle. 3 columns wide (the tokens), 4 rows deep (the features).

# Shape: (1, 3, 4) — [Batch=1, Time=3, Channels=4]

# 3. The Position Overlay (pos_emb)
# Code: pos_emb = self.position_embedding_table(torch.arange(T))
# The model generates a second grid of the exact same size. This grid doesn't care about the tokens; it only cares about the seats (Seat 0, Seat 1, Seat 2).

# Seat 0 generates its own 4 numbers: [0.0, 0.1, 0.0, -0.1].

# Seat 1 generates its own 4 numbers.

# Seat 2 generates its own 4 numbers.

# The Grid: A second rectangle, identical in size: 3 columns wide, 4 rows deep.

# Shape: (3, 4) — [Time=3, Channels=4]

# 4. The Fusion (x = tok_emb + pos_emb)
# Code: x = tok_emb + pos_emb
# You take the two identical rectangles and smash them together, adding the numbers on top of each other.

# The Grid: The rectangle doesn't change size. It is still 3 columns wide and 4 rows deep. But the numbers inside have been updated.

# Shape: (1, 3, 4) — [Batch=1, Time=3, Channels=4]

# 5. The Final Squeeze (logits = self.lm_head(x))
# Code: logits = self.lm_head(x)
# We need to guess the next character. We have 10 characters in our vocabulary, but our grid is currently 4 rows deep.
# The Linear layer acts like a mathematical vise grip. It squeezes the 4 rows (C) and stretches them out until there are exactly 10 rows (vocab_size).

# The Grid: The grid is still 3 columns wide (the 3 tokens). But now, instead of being 4 rows deep, it is 10 rows deep. Each of those 10 rows holds a score for a specific character in your vocabulary.

# Shape: (1, 3, 10) — [Batch=1, Time=3, Vocab=10]
class BigramLanguageModel(nn.Module):#Lookup table for next token predictor
  def __init__(self,vocab_size):
    super().__init__()
    self.token_embedding_table=nn.Embedding(vocab_size,n_embd)#creates a 2d sheet#The "What" Dictionary. It maps the 65 vocabulary characters to 32-feature dossiers (n_embd).
    self.position_embedding_table=nn.Embedding(block_size,n_embd)#self.position_embedding_table: The "Where" Dictionary. It has block_size (e.g., 8) rows. It contains a 32-feature dossier for "Seat 0", "Seat 1", "Seat 2", etc.
    self.lm_head=nn.Linear(n_embd,vocab_size)#self.lm_head: The Translator. It takes a 32-feature dossier and translates it back into 65 vocabulary guesses.

  def forward(self,idx,targets=None):
    B,T=idx.shape #B is batch size and T is block size
    tok_emb=self.token_embedding_table(idx)#(B,T,C) #Hey PyTorch, the user just typed the letter 'H' (which is integer ID 34). Please go to the spreadsheet and give me exactly Row 34.
    pos_emb=self.position_embedding_table(torch.arange(T)) #(B,T,C)
    x=tok_emb+pos_emb #(B,T,C)
    logits=self.lm_head(x)#(B,T,vocab_size)

    if targets is None:
      loss=None
    else:
      B,T,C=logits.shape
      logits=logits.view(B*T,C)
      targets=targets.view(B*T)
      loss=F.cross_entropy(logits,targets)#F.cross entropy needs a 2d logit space and 1d target space

    return logits,loss


#   # Iteration 1:
# idx = [[18, 47, 56]]  # Current: "hel"
# logits = (1, 3, 65)
# logits[:, -1, :] → Use position 2 → Sample token 56 → 'l'
# idx = [[18, 47, 56, 56]]  # Now: "hell"

# # Iteration 2:
# idx = [[18, 47, 56, 56]]  # Current: "hell"
# logits = (1, 4, 65)
# logits[:, -1, :] → Use position 3 (new last) → Sample token 58 → 'o'
# idx = [[18, 47, 56, 56, 58]]  # Now: "hello"

  def generate(self,idx,max_new_tokens):
    for _ in range(max_new_tokens):
      idx_cond = idx[:, -block_size:]
      logits,loss=self(idx_cond)

      logits=logits[:,-1,:]
      probs=F.softmax(logits,dim=-1)
      idx_next=torch.multinomial(probs,num_samples=1)#picks max probability value
      idx=torch.cat((idx,idx_next),dim=1)
    return idx

model=BigramLanguageModel(vocab_size)
logits,loss=model(xb,yb)
print(logits)
print("------------------------------------------------------------------------")
print(loss)
print("------------------------------------------------------------------------")
print(decode(model.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=100)[0].tolist()))


tensor([[ 1.0933, -0.0464, -0.4168,  ..., -0.2151,  0.2817,  0.1784],
        [ 0.9475,  0.5316, -0.2714,  ..., -0.3369,  0.9493, -0.8088],
        [-0.0041,  0.4451,  0.9703,  ..., -0.0283, -0.7513,  1.0525],
        ...,
        [ 0.1821, -0.1342,  0.7949,  ...,  1.0528, -0.2140, -0.4392],
        [ 1.1231,  0.2577, -0.0298,  ..., -0.0136,  1.8571,  1.4677],
        [-0.6128, -1.3217,  0.3355,  ...,  0.3302,  0.9465,  0.3918]],
       grad_fn=<ViewBackward0>)
------------------------------------------------------------------------
tensor(4.6272, grad_fn=<NllLossBackward0>)
------------------------------------------------------------------------

SmVddomOVWydk3'BrlK
QduWGGHPmiu&UXBlIHTZ'yfsDuEtqWPUlOZt&-lV&qBohwN.l;N3z:miimwvg,gAo3EPN3hOw$!VyTuE


In [58]:
@torch.no_grad()# We are never gonna call backward on this
def estimate_loss():
    out = {}
    model.eval()

    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)

        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()

        out[split] = losses.mean()

    model.train()
    return out

In [59]:
#creating a Pytorch optimizer
optimizer=torch.optim.AdamW(model.parameters(),lr=1e-3)

In [60]:
batch_size=32
for steps in range(10000):
  xb,yb=get_batch('train')
  logits,loss=model(xb,yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())


2.3611717224121094


In [61]:
print(decode(model.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=300)[0].tolist()))


Tonilak Bur s thupow ced w.
SEHe, ase ic parl ath haagr t w wane he herche ou INVat? US:
Wo bof,
Whind t myeaverentcooshe, whiks d.
D pat'lsp
Thad! sot!
Yod t ou thipleain du t an.
ONIUCI he.
LLeste t, ce, m tane ssichalispres lldofr, ther ionomay:
FLOMou IEETIINO:
WA we kimmans o wlake, be!
Wh y ti


Trick in self attention


In [62]:
torch.manual_seed(1332)
B,T,C=4,8,2
x=torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [63]:
xbow=torch.zeros((B,T,C))
for b in range(B):
  for t in range(T):
    xprev=x[b,:t+1] #(T,C) dimension
    xbow[b,t]=torch.mean(xprev,0)#0th dimension
#We are averaging and saving values across time
#The Channel dimension is literally an arena where 65 possible next characters are competing. The one with the highest logit is the model's absolute best guess for what happens next, and the other 64 will have lower scores.

In [64]:
x[0]

tensor([[ 0.6828, -0.1091],
        [ 1.6661,  0.0601],
        [-0.3547, -0.3625],
        [-0.4134,  0.5899],
        [ 0.1349,  0.9516],
        [-0.0464, -2.1700],
        [ 0.7447,  1.7339],
        [-0.5819,  0.1811]])

In [65]:
xbow[0]

tensor([[ 0.6828, -0.1091],
        [ 1.1744, -0.0245],
        [ 0.6647, -0.1372],
        [ 0.3952,  0.0446],
        [ 0.3431,  0.2260],
        [ 0.2782, -0.1733],
        [ 0.3448,  0.0991],
        [ 0.2290,  0.1094]])

In [66]:
# # Example with T=3
# wei = torch.tril(torch.ones(3, 3))
# # wei = [[1, 0, 0],
# #        [1, 1, 0],
# #        [1, 1, 1]]

# # Sum each row, keepdim=True makes it shape (3, 1)
# row_sums = wei.sum(1, keepdim=True)
# # row_sums = [[1],   <- sum of row 0
# #             [2],   <- sum of row 1
# #             [3]]   <- sum of row 2

# # Division uses broadcasting: each row divided by its own sum
# wei = wei / row_sums
# # Row 0: [1, 0, 0] / 1 = [1.0, 0.0, 0.0]
# # Row 1: [1, 1, 0] / 2 = [0.5, 0.5, 0.0]
# # Row 2: [1, 1, 1] / 3 = [0.33, 0.33, 0.33] wei=torch.tril(torch.ones(T,T))
wei=torch.tril(torch.ones(T,T))
wei=wei/wei.sum(1,keepdim=True)
xbow2=wei@x #Creates a batch dimension
torch.allclose(xbow,xbow2)

True

In [67]:
torch.manual_seed(1337)

In [73]:
#single head performing self-attention
#every single token will emit a query(what am I looking for?) and a key(what do I contain?) and value(If you find me interesting here's what I will communicate to you)
B,T,C=4,8,32
x=torch.randn(B,T,C)
head_size=16
key=nn.Linear(C,head_size,bias=False)## nn.linear only modifies 3rd axis
query=nn.Linear(C,head_size,bias=False)
value=nn.Linear(C,head_size,bias=False)
k=key(x) #(B,T,16) because we are projecting the 32 dimensional input down to 16 dimensions for the key and query
q=query(x) #(B,T,16)
wei=q@k.transpose(-2,-1)* (head_size**-0.5) #(B,T,16) @ (B,16,T) → (B,T,T)

tril=torch.tril(torch.ones(T,T))
wei=wei.masked_fill(tril==0,float('-inf'))
wei=F.softmax(wei,dim=-1)#self attention trick
out=wei@x #(B,T,T) @ (B,T,C) → (B,T,C)

out.shape

v=value(x)
out=wei@x


The above block is a decoder block, since we are using masked fill and tril, we are not allowing all tokens to talk to each other.
If we want all tokens to talk to each other, we would have to use an encoder block and that would be without the masked fill

Cross attention is when we pull information from a separate set of nodes to our nodes to learn from

In [72]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.6912, 0.3088, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0071, 0.3294, 0.6634, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0606, 0.5145, 0.0878, 0.3370, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1785, 0.7020, 0.0152, 0.0336, 0.0708, 0.0000, 0.0000, 0.0000],
        [0.0487, 0.0707, 0.2963, 0.2988, 0.2677, 0.0177, 0.0000, 0.0000],
        [0.0627, 0.0537, 0.1817, 0.0853, 0.3449, 0.0356, 0.2360, 0.0000],
        [0.0264, 0.0387, 0.1633, 0.0563, 0.0641, 0.0538, 0.3835, 0.2139]],
       grad_fn=<SelectBackward0>)

Softmax would be way too peaky with high variance towards the largest logit, if its used directly, hence wei is divided by the sqrt(head size) before softmax is used

In [84]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.209729 M parameters
step 0: train loss 4.4116, val loss 4.4022
step 100: train loss 2.6568, val loss 2.6670
step 200: train loss 2.5090, val loss 2.5058
step 300: train loss 2.4197, val loss 2.4338
step 400: train loss 2.3502, val loss 2.3563
step 500: train loss 2.2963, val loss 2.3128
step 600: train loss 2.2411, val loss 2.2499
step 700: train loss 2.2056, val loss 2.2193
step 800: train loss 2.1634, val loss 2.1866
step 900: train loss 2.1248, val loss 2.1512
step 1000: train loss 2.1025, val loss 2.1299
step 1100: train loss 2.0686, val loss 2.1178
step 1200: train loss 2.0380, val loss 2.0795
step 1300: train loss 2.0250, val loss 2.0638
step 1400: train loss 1.9907, val loss 2.0355
step 1500: train loss 1.9700, val loss 2.0300
step 1600: train loss 1.9632, val loss 2.0484
step 1700: train loss 1.9397, val loss 2.0120
step 1800: train loss 1.9096, val loss 1.9968
step 1900: train loss 1.9093, val loss 1.9880
step 2000: train loss 1.8852, val loss 1.9972
step 2100: train loss 1.

KeyboardInterrupt: 