In [3]:
import urllib
url="https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
filename="input.txt"
urllib.request.urlretrieve(url,filename)

('input.txt', <http.client.HTTPMessage at 0x2540f47abf0>)

In [4]:
with open("input.txt",'r',encoding="utf-8") as f: #utf-8 encoding takes 1-4 bytes per character(variable) unlike ASCII that takes 8 bits per character
  text=f.read()                                   #highly relevant for tokenizers

In [5]:
print("The length of the dataset is:", len(text))

The length of the dataset is: 1115394


In [6]:
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [17]:
chars=sorted(set(text))
seen_string="".join(chars)
print(seen_string)
vocab_size=len(chars)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


In [18]:
stoi={ch:i for i,ch in enumerate(chars)}
print(stoi)#string to integer
itos={i:ch for i,ch in enumerate(chars)}
print(itos)#integer to string

def encode(s): #Any string can be converted into a list of numbers(based on stoi dict)
  string_val=[]
  for i in s:
    string_val.append(stoi[i])
  return string_val

def decode(i): #Any set of numbers can be converted into a string(based on itos dict)
  string_val=""
  for k in i:
    string_val+=(itos[k])
  return string_val


print(encode("hi there"))
print(decode(encode("hi there")))

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}
{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i',

In [19]:
import torch
data=torch.tensor(encode(text),dtype=torch.long)
print(data.shape,data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [20]:
n=int(0.9*len(data))
train_data=data[:n]
val_data=data[n:]

In [11]:
block_size=8

In [12]:
x=train_data[:block_size]#sliding window 0-7
y=train_data[1:block_size+1]# sliding window 1-8
print(x)
print(y)

tensor([18, 47, 56, 57, 58,  1, 15, 47])
tensor([47, 56, 57, 58,  1, 15, 47, 58])


In [13]:
for t in range(block_size):
  context=x[:t+1]
  target=y[t]
  print(f"when input is {context}, output is {target}")

when input is tensor([18]), output is 47
when input is tensor([18, 47]), output is 56
when input is tensor([18, 47, 56]), output is 57
when input is tensor([18, 47, 56, 57]), output is 58
when input is tensor([18, 47, 56, 57, 58]), output is 1
when input is tensor([18, 47, 56, 57, 58,  1]), output is 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]), output is 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), output is 58


In [21]:
torch.manual_seed(1337)
batch_size=4 #How many independent sequences will we process in parallel?
block_size=8
def get_batch(split):
  #generate a small batch of data of inputs x and targets y
  new_data=train_data if split=='train' else val_data
  ix=torch.randint(len(new_data)-block_size,(batch_size,))#Taking 4 random numbers
  x=torch.stack([new_data[i:i+block_size] for i in ix]) #  Randomly taking continuous block_size length chunk form the data(batch size(4) of them and stacking)
  y=torch.stack([new_data[i+1:i+block_size+1] for i in ix] )
  return x,y

In [22]:
xb,yb=get_batch('train')
print("inputs:")
print(xb.shape)
print(xb)
print("outputs:")
print(yb.shape)
print(yb)

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
outputs:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


In [ ]:
# BIGRAM EMBEDDING TABLE (vocab_size × vocab_size)

#            Next Token Predictions →
#            a    b    c    d    e   ...
#          ┌─────────────────────────────┐
#       a  │ 0.2  0.5 -0.1  0.3  0.8 ... │ ← Scores for "a→?"
#       b  │ 0.7 -0.3  0.9  0.1  0.4 ... │ ← Scores for "b→?"
# Current c │-0.5  0.6  0.2  0.8 -0.2 ... │ ← Scores for "c→?"
# Token  d │ 0.4  0.1 -0.7  0.5  0.6 ... │ ← Scores for "d→?"
#       e  │ 0.9  0.3  0.4 -0.1  0.2 ... │ ← Scores for "e→?"
#      ... │ ...  ...  ...  ...  ... ... │
#          └─────────────────────────────┘
# ```

# **How it works:**
# ```
# Example: Predict next token after "c"

# 1. Input: token "c" → Look up row 'c'

#    Row c: [-0.5, 0.6, 0.2, 0.8, -0.2, ...]
#            ↑    ↑    ↑    ↑     ↑
#            a    b    c    d     e

# 2. These are logits (raw scores)

# 3. Apply softmax → probabilities:
#    [0.05, 0.15, 0.10, 0.20, 0.06, ...]

# 4. Highest score = 'd' (0.8)
#    → Most likely next token is 'd'
#    → Model predicts: "c" → "d"

# Your data:
# xb = [[18, 47, 56, 57, 58, 1, 15, 47],    # Batch 0: 8 token indices
#       [13, 52, 45, 43, 57, 43, 1, 39],     # Batch 1: 8 token indices
#       [58, 46, 43, 1, 58, 46, 43, 1],      # Batch 2: 8 token indices
#       [39, 52, 41, 43, 1, 58, 46, 43]]     # Batch 3: 8 token indices
# # Shape: (4, 8)

# yb = [[47, 56, 57, 58, 1, 15, 47, 57],    # Targets shifted by 1
#       [52, 45, 43, 57, 43, 1, 39, 58],
#       [46, 43, 1, 58, 46, 43, 1, 39],
#       [52, 41, 43, 1, 58, 46, 43, 1]]
# # Shape: (4, 8)

# # Pass to model:
# out = m(xb, yb)
# ```

# **What happens:**
# ```
# For EACH token index in xb, look up that row in embedding table:

# Batch 0, Position 0: Token 18 → Look up row 18 → Get [65 scores]
# Batch 0, Position 1: Token 47 → Look up row 47 → Get [65 scores]
# Batch 0, Position 2: Token 56 → Look up row 56 → Get [65 scores]
# ...
# Batch 3, Position 7: Token 43 → Look up row 43 → Get [65 scores]
#For each token you get 65 scores

# PAGE 1 (the input xb): 4 rows × 8 columns
# xb = [[18, 47, 56, 57, 58,  1, 15, 47],
#       [13, 52, 45, 43, 57, 43,  1, 39],
#       [58, 46, 43,  1, 58, 46, 43,  1],
#       [39, 52, 41, 43,  1, 58, 46, 43]]
# ```

# **logits = A THICK BOOK with 4 PAGES (one per batch):**

# ---

# **📄 PAGE 1 (Batch 0):** 8 rows × 65 columns
# ```
# Position 0 (token 18): [0.2, 0.5, 0.1, ..., 0.9, ...]  ← 65 scores
# Position 1 (token 47): [0.3, 0.7, 0.2, ..., 0.4, ...]  ← 65 scores
# Position 2 (token 56): [0.1, 0.4, 0.8, ..., 0.6, ...]  ← 65 scores
# Position 3 (token 57): [0.5, 0.2, 0.3, ..., 0.7, ...]  ← 65 scores
# Position 4 (token 58): [0.6, 0.8, 0.1, ..., 0.5, ...]  ← 65 scores
# Position 5 (token  1): [0.4, 0.3, 0.9, ..., 0.2, ...]  ← 65 scores
# Position 6 (token 15): [0.7, 0.1, 0.4, ..., 0.8, ...]  ← 65 scores
# Position 7 (token 47): [0.2, 0.6, 0.5, ..., 0.3, ...]  ← 65 scores
# ```

# ---

# **📄 PAGE 2 (Batch 1):** 8 rows × 65 columns
# ```
# Position 0 (token 13): [0.4, 0.2, 0.7, ..., 0.1, ...]  ← 65 scores
# Position 1 (token 52): [0.8, 0.3, 0.5, ..., 0.6, ...]  ← 65 scores
# Position 2 (token 45): [0.1, 0.9, 0.2, ..., 0.4, ...]  ← 65 scores
# ... (6 more rows)
# ```

# ---

# **📄 PAGE 3 (Batch 2):** 8 rows × 65 columns
# ```
# Position 0 (token 58): [0.6, 0.8, 0.1, ..., 0.5, ...]  ← 65 scores
# Position 1 (token 46): [0.3, 0.5, 0.7, ..., 0.2, ...]  ← 65 scores
# ... (6 more rows)
# ```

# ---

# **📄 PAGE 4 (Batch 3):** 8 rows × 65 columns
# ```
# Position 0 (token 39): [0.5, 0.4, 0.6, ..., 0.9, ...]  ← 65 scores
# Position 1 (token 52): [0.8, 0.3, 0.5, ..., 0.6, ...]  ← 65 scores
# ... (6 more rows)

#NOW ITS JUST CHANNELS AND NOT ALL VOCAB SIZE
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)
n_embd=32

class BigramLanguageModel(nn.Module):#Lookup table for next token predictor
  def __init__(self,vocab_size):
    super().__init__()
    self.token_embedding_table=nn.Embedding(vocab_size,n_embd)
    self.position_embedding_table=nn.Embedding(block_size,n_embd)
    self.lm_head=nn.Linear(n_embd,vocab_size)

  def forward(self,idx,targets=None):
    tok_emb=self.token_embedding_table(idx) #(B,T,C)
    pos_emb=self.position_embedding_table(torch.arange(T, device=idx.device)) #(T,C)
    x=tok_emb+pos_emb #(B,T,C)
    logits=self.lm_head(x)#(B,T,vocab_size)

    if targets is None:
      loss=None
    else:
      B,T,C=logits.shape
      logits=logits.view(B*T,C)
      targets=targets.view(B*T)
      loss=F.cross_entropy(logits,targets)#F.cross entropy needs a 2d logit space and 1d target space

    return logits,loss


#   # Iteration 1:
# idx = [[18, 47, 56]]  # Current: "hel"
# logits = (1, 3, 65)
# logits[:, -1, :] → Use position 2 → Sample token 56 → 'l'
# idx = [[18, 47, 56, 56]]  # Now: "hell"

# # Iteration 2:
# idx = [[18, 47, 56, 56]]  # Current: "hell"
# logits = (1, 4, 65)
# logits[:, -1, :] → Use position 3 (new last) → Sample token 58 → 'o'
# idx = [[18, 47, 56, 56, 58]]  # Now: "hello"

  def generate(self,idx,max_new_tokens):
    for _ in range(max_new_tokens):
      logits,loss=self(idx)
      logits=logits[:,-1,:]
      probs=F.softmax(logits,dim=-1)
      idx_next=torch.multinomial(probs,num_samples=1)#picks max probability value
      idx=torch.cat((idx,idx_next),dim=1)
    return idx

model=BigramLanguageModel(vocab_size)
logits,loss=model(xb,yb)
print(logits)
print("------------------------------------------------------------------------")
print(loss)
print("------------------------------------------------------------------------")
print(decode(model.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=100)[0].tolist()))


tensor([[ 0.8480,  0.6846,  0.0579,  ...,  0.0848,  1.4014,  0.3483],
        [ 0.1814, -0.4525,  0.4104,  ..., -0.1960, -0.5161,  0.4413],
        [ 0.0739, -0.4465, -0.3112,  ...,  0.2526,  0.9272,  0.3871],
        ...,
        [-0.0101,  0.6622,  0.2048,  ...,  0.0535,  0.2764,  0.0566],
        [-0.0658, -1.1870, -1.3186,  ...,  0.3544,  0.8059,  0.1195],
        [ 0.2294, -0.2674,  0.2987,  ..., -0.5195, -0.1519,  0.9036]],
       grad_fn=<ViewBackward0>)
------------------------------------------------------------------------
tensor(4.3267, grad_fn=<NllLossBackward0>)
------------------------------------------------------------------------

SmWddomOVWydk3'B;MJ
Q
aOGGHPx?
&UXBcIHTZ'qPsDuEtqWPUlOZt&-lV&jBohwN.Y;N3k:mximwvg,gAo3EPN3hOY$!VqTuE


In [ ]:
@torch.no_grad()# We are never gonna call backward on this
def estimate_loss():
    out = {}
    model.eval()

    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)

        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()

        out[split] = losses.mean()

    model.train()
    return out

In [ ]:
#creating a Pytorch optimizer
optimizer=torch.optim.AdamW(model.parameters(),lr=1e-3)

In [31]:
batch_size=32
for steps in range(10000):
  xb,yb=get_batch('train')
  logits,loss=model(xb,yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())


4.725085258483887


In [32]:
print(decode(model.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=300)[0].tolist()))


lsulgYCV'v&Q&vCuDuqfSmgSVTxMCZI-:w:eDOUevrdfNHI!zkcktRyF$&DoiMusERjuUzPyhSP.&l-e;ALQ?!!KHn'Me,SulxEzPhsTGjKcoUAKDhaXESqL!uwU,So.aV;vky,SP vn!uRJyJPsupAcsqHOvNCjWM:epu;f,SQOIoTkXI$-R.i-zXxfulgyQ?BBSZvU'yDHIwD:zMlFd:CviCS Cz;Ku$EGlg
FErhPyAV&AcC&'atDo,o
ayY!!UznUAc;Dy$gC-oRCDKIcM'dYcLNpbD3QJa!srdzbco&


Trick in self attention


In [35]:
torch.manual_seed(1332)
B,T,C=4,8,2
x=torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
xbow=torch.zeros((B,T,C))
for b in range(B):
  for t in range(T):
    xprev=x[b,:t+1] #(T,C) dimension
    xbow[b,t]=torch.mean(xprev,0)#0th dimension
#We are averaging and saving values across time
#The Channel dimension is literally an arena where 65 possible next characters are competing. The one with the highest logit is the model's absolute best guess for what happens next, and the other 64 will have lower scores.

In [37]:
x[0]

tensor([[ 0.6828, -0.1091],
        [ 1.6661,  0.0601],
        [-0.3547, -0.3625],
        [-0.4134,  0.5899],
        [ 0.1349,  0.9516],
        [-0.0464, -2.1700],
        [ 0.7447,  1.7339],
        [-0.5819,  0.1811]])

In [38]:
xbow[0]

tensor([[ 0.6828, -0.1091],
        [ 1.1744, -0.0245],
        [ 0.6647, -0.1372],
        [ 0.3952,  0.0446],
        [ 0.3431,  0.2260],
        [ 0.2782, -0.1733],
        [ 0.3448,  0.0991],
        [ 0.2290,  0.1094]])

In [ ]:
# # Example with T=3
# wei = torch.tril(torch.ones(3, 3))
# # wei = [[1, 0, 0],
# #        [1, 1, 0],
# #        [1, 1, 1]]

# # Sum each row, keepdim=True makes it shape (3, 1)
# row_sums = wei.sum(1, keepdim=True)
# # row_sums = [[1],   <- sum of row 0
# #             [2],   <- sum of row 1
# #             [3]]   <- sum of row 2

# # Division uses broadcasting: each row divided by its own sum
# wei = wei / row_sums
# # Row 0: [1, 0, 0] / 1 = [1.0, 0.0, 0.0]
# # Row 1: [1, 1, 0] / 2 = [0.5, 0.5, 0.0]
# # Row 2: [1, 1, 1] / 3 = [0.33, 0.33, 0.33] wei=torch.tril(torch.ones(T,T))
wei=torch.tril(torch.ones(T,T))
wei=wei/wei.sum(1,keepdim=True)
xbow2=wei@x #Creates a batch dimension
torch.allclose(xbow,xbow2)

True

In [44]:
torch.manual_seed(1337)

In [ ]:
#single head performing self-attention
#every single token will emit a query(what am I looking for?) and a key(what do I contain?)
B,T,C=4,8,32
x=torch.randn(B,T,C)
head_size=16
key=nn.Linear(n_embd,head_size,bias=False)## nn.linear only modifies 3rd axis
query=nn.Linear(n_embd,head_size,bias=False)
k=key(x) #(B,T,16) because we are projecting the 32 dimensional input down to 16 dimensions for the key and query
q=query(x) #(B,T,16)
wei=q@k.transpose(-2,-1) #(B,T,16) @ (B,16,T) → (B,T,T)

tril=torch.tril(torch.ones(T,T))
wei=wei.masked_fill(tril==0,float('-inf'))#masking out upper triangular part of the matrix
wei=F.softmax(wei,dim=-1)#self attention trick
out=wei@x #(B,T,T) @ (B,T,C) → (B,T,C)